# Generated by Django 5.2.8 on 2025-11-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_options_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-id'], 'verbose_name': 'Tag Table', 'verbose_name_plural': 'Tags Table'},
        ),
    ]
